apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-09T10:44:12Z"
  labels:
    run: static-webpage
  name: static-webpage
  resourceVersion: "16923"
  uid: d3f52a0d-bfd6-439f-891f-b30e79c77238
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30999
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: static-webpage
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
