apiVersion: v1
kind: Pod
metadata:
  labels:
    run: static-webpage
  name: static-webpage
spec:
  containers:
  - image: 0xsydtry/static-webpage
    name: static-webpage
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
